# Generated by Django 5.0.7 on 2024-07-31 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spi', models.FloatField()),
                ('cpi', models.FloatField()),
                ('planned_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earned_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
                ('completion_percentage', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
            ],
        ),
    ]
